services:
  db:
    image: "postgres:14.1-alpine"
    restart: always
    container_name: "VIA_TABLOID_DB"
    ports:
      - "5432:5432"   
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=assignment-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  backend:
    build:
      context: ./
    container_name: "VIA_TABLOID_BACKEND"
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - spring.datasource.url=jdbc:postgresql://db:5432/assignment-db  # connect to db service on 5432
      - spring.datasource.username=postgres
      - spring.datasource.password=postgres
      - spring.jpa.hibernate.show-sql=true
      - spring.jpa.hibernate.ddl-auto=update

  frontend:
    build:
      context: ./viatab-frontend
    container_name: "VIA_TABLOID_FRONTEND"
    ports:
      - "8090:8090"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:8080   # connect to backend service on 9090
    volumes:
      - ./viatab-frontend:/app
volumes:
  db:
    driver: local
