# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: viatab-frontend-service
  labels:
    app: viatab-frontend
spec:
  selector:
    app: viatab-frontend  # Matches the label of the frontend deployment
  ports:
    - protocol: TCP
      port: 80  # Expose port 80 for the frontend service
      targetPort: 80  # Port exposed by the container
  type: NodePort  # Expose externally when using Minikube

---

# Backend Service
apiVersion: v1
kind: Service
metadata:
  name: viatab-backend-service
  labels:
    app: viatab-backend
spec:
  selector:
    app: viatab-backend  # Matches the label of the backend deployment
  ports:
    - protocol: TCP
      port: 8080  # Expose port 8080 for the backend service
      targetPort: 8080  # Port exposed by the container
  type: NodePort  # Expose externally when using Minikube

---

# Database Service (PostgreSQL)
apiVersion: v1
kind: Service
metadata:
  name: viatab-db-service
  labels:
    app: viatab-db
spec:
  selector:
    app: viatab-db  # Matches the label of the database deployment
  ports:
    - protocol: TCP
      port: 5432  # Expose port 5432 for PostgreSQL database service
      targetPort: 5432  # Port exposed by the container
  clusterIP: None  # For database, use None to create a headless service (optional here)
