apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - env:
            - name: spring.datasource.password
              value: postgres
            - name: spring.datasource.url
              value: jdbc:postgresql://db:5432/assignment-db
            - name: spring.datasource.username
              value: postgres
            - name: spring.jpa.hibernate.ddl-auto
              value: update
            - name: spring.jpa.hibernate.show-sql
              value: "true"
          image: backend
          name: via-tabloid-backend
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
