apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: frontend
    spec:
      containers:
        - env:
            - name: REACT_APP_API_URL
              value: http://backend:8080
          image: frontend
          name: via-tabloid-frontend
          ports:
            - containerPort: 8090
              protocol: TCP
          volumeMounts:
            - mountPath: /app
              name: frontend-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: frontend-cm0
          name: frontend-cm0
